name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Test SSH Connectivity
        run: |
          sudo apt-get update
          sudo apt-get install -y netcat
          nc -zv ${{ secrets.PI_HOST }} 22
        continue-on-error: true  # Allows the workflow to continue even if this step fails

      - name: Deploy to Raspberry Pi
        uses: appleboy/scp-action@v0.1.13  # Updated to a newer version
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          source: "build/*"
          target: "/var/www/PersonalPortfolio"
          debug: true
          port: 22
          timeout: 60s
          command_timeout: 15m

      - name: Restart Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
